# [START cloudbuild]
steps:
  ### Build
  - id: 'build'
    name: 'gcr.io/cloud-builders/mvn'
    args: [
      'clean',
      'package',
      '-Dmaven.test.skip=true'
    ]
  ### docker Build
  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/hidoldori-lab-cicd-project/hidoldori-web:$SHORT_SHA'
      - '.'
  ### docker push
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/hidoldori-lab-cicd-project/hidoldori-web:$SHORT_SHA'
  # This step clones the hidoldori-env repository
  - id: 'Clone env repository'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud source repos clone hidoldori-env && \
        cd hidoldori-env && \
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
  # This step generates the new manifest
  - id: 'Generate manifest'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed "s/12345/6789/g" kubernetes.yaml.tpl | \
        sed "s/SHORT_SHA/${SHORT_SHA}/g" > hidoldori-env/kubernetes.yaml
  # This step pushes the manifest back to hidoldori-env
  - id: 'Push manifest'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        cd hidoldori-env && \
        git add kubernetes.yaml && \
        git commit -m "Deploying image gcr.io/${PROJECT_ID}/hidoldori-web:${SHORT_SHA}
        Built from commit ${COMMIT_SHA} of repository hidoldori-web
        Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
        git push origin master

# [END cloudbuild-trigger-cd]