steps:
  ### Build
  - id: 'build'
    name: 'gcr.io/cloud-builders/mvn'
    args: [
      'clean',
      'package',
      '-Dmaven.test.skip=true'
    ]
  ### docker Build
  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/hidoldori-lab-project/hidoldori-web:$COMMIT_SHA'
      - '.'
  ### docker Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push asia.gcr.io/hidoldori-lab-project/hidoldori-web:$COMMIT_SHA
  ### deploy to dev
  - id: 'deploy dev'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        PROJECT=$$(gcloud config get-value core/project)
        gcloud container clusters get-credentials "$${CLOUDSDK_CONTAINER_CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${CLOUDSDK_COMPUTE_ZONE}"
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Service
        metadata:
          name: hidoldori-web
          labels:
            app: hidoldori-web
        spec:
          ports:
            - port: 8080
              targetPort: 8080
          selector:
            app: hidoldori-web
          type: LoadBalancer
        EOF
        cat <<EOF | kubectl apply -f -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: hidoldori-web
          labels:
            app: hidoldori-web
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: hidoldori-web
          template:
            metadata:
              labels:
                app: hidoldori-web
            spec:
              containers:
                - name: hidoldori-web
                  image: asia.gcr.io/hidoldori-lab-project/hidoldori-web:$COMMIT_SHA
                  ports:
                    - containerPort: 8080
        EOF
options:
  env:
    #    # location/name of GKE cluster (used by all kubectl commands)
    - CLOUDSDK_COMPUTE_ZONE=us-central1-b
    - CLOUDSDK_CONTAINER_CLUSTER=hello-lab-cluster